# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'absensi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 380)
        MainWindow.setMinimumSize(QtCore.QSize(300, 380))
        MainWindow.setMaximumSize(QtCore.QSize(300, 380))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(150, 90, 113, 20))
        self.inputName.setObjectName("inputName")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 47, 13))
        self.label_3.setObjectName("label_3")
        self.inputKelas = QtWidgets.QLineEdit(self.centralwidget)
        self.inputKelas.setGeometry(QtCore.QRect(150, 140, 113, 20))
        self.inputKelas.setObjectName("inputKelas")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 101, 16))
        self.label_4.setObjectName("label_4")
        self.inputJam = QtWidgets.QLineEdit(self.centralwidget)
        self.inputJam.setGeometry(QtCore.QRect(150, 190, 113, 20))
        self.inputJam.setObjectName("inputJam")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 240, 101, 16))
        self.label_5.setObjectName("label_5")
        self.inputMapel = QtWidgets.QLineEdit(self.centralwidget)
        self.inputMapel.setGeometry(QtCore.QRect(150, 240, 113, 20))
        self.inputMapel.setObjectName("inputMapel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 300, 221, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ABSENSI KELAS 3F"))
        self.label_2.setText(_translate("MainWindow", "NAMA :"))
        self.label_3.setText(_translate("MainWindow", "KELAS :"))
        self.label_4.setText(_translate("MainWindow", "JAM HADIR :"))
        self.label_5.setText(_translate("MainWindow", "MATA PELAJARAN :"))
        self.pushButton.setText(_translate("MainWindow", "KIRIM"))
        self.pushButton.clicked.connect(self.kirim)

    def kirim(self):
        import pymysql

        db = pymysql.connect(
            host="localhost",
            user="root",
            password="",
            database="absen"
        )

        cursor = db.cursor()
        nama = self.inputName.text()
        kelas = self.inputKelas.text()
        jam = self.inputJam.text()
        mapel = self.inputMapel.text()
        sql = F"""INSERT INTO KEHADIRAN VALUES (
            '{nama}', '{kelas}', '{jam}', '{mapel}' );
        """

        cursor.execute(sql)
        db.commit()
        db.close()
        print("====== jawaban anda telah terekam =======")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setWindowTitle("ABSENSI")
    MainWindow.show()
    sys.exit(app.exec_())
