# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'daftarSBM.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.inputNama = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNama.setGeometry(QtCore.QRect(140, 80, 113, 20))
        self.inputNama.setObjectName("inputNama")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 47, 13))
        self.label_3.setObjectName("label_3")
        self.inputTTL = QtWidgets.QLineEdit(self.centralwidget)
        self.inputTTL.setGeometry(QtCore.QRect(140, 140, 113, 20))
        self.inputTTL.setObjectName("inputTTL")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 300, 47, 13))
        self.label_6.setObjectName("label_6")
        self.inputSEKOLAH = QtWidgets.QLineEdit(self.centralwidget)
        self.inputSEKOLAH.setGeometry(QtCore.QRect(140, 200, 113, 20))
        self.inputSEKOLAH.setObjectName("inputSEKOLAH")
        self.inputJURUSAN = QtWidgets.QLineEdit(self.centralwidget)
        self.inputJURUSAN.setGeometry(QtCore.QRect(140, 250, 113, 20))
        self.inputJURUSAN.setObjectName("inputJURUSAN")
        self.inputNIS = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNIS.setGeometry(QtCore.QRect(140, 300, 113, 20))
        self.inputNIS.setObjectName("inputNIS")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 340, 171, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DAFTAR SBMPTN"))
        self.label_2.setText(_translate("MainWindow", "NAMA :"))
        self.label_3.setText(_translate("MainWindow", "TTL :"))
        self.label_4.setText(_translate("MainWindow", "ASAL SEKOLAH :"))
        self.label_5.setText(_translate("MainWindow", "JURUSAN :"))
        self.label_6.setText(_translate("MainWindow", "NIS :"))
        self.pushButton.setText(_translate("MainWindow", "DAFTAR"))
        self.pushButton.clicked.connect(self.daftar)


    def daftar(self):
        import pymysql

        db = pymysql.connect(
            host="localhost",
            user="root",
            password="",
            database="daftarsbm"
        )
        cursor = db.cursor()
        nama = self.inputNama.text()
        TTL = self.inputTTL.text()
        asalSekolah = self.inputSEKOLAH.text()
        jurusan = self.inputJURUSAN.text()
        nis = self.inputNIS.text()
        sql = f"""INSERT INTO daftar values
        ('{nama}', '{TTL}', '{asalSekolah}', '{jurusan}', '{nis}' );
        """

        cursor.execute(sql)
        db.commit()
        db.close()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
