# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 258)
        QMainWindow.setWindowTitle(self,"LOGIN")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 71, 21))
        self.label.setObjectName("LOGIN")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.inputId = QtWidgets.QLineEdit(self.centralwidget)
        self.inputId.setGeometry(QtCore.QRect(160, 60, 113, 20))
        self.inputId.setObjectName("inputId")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 61, 20))
        self.label_3.setObjectName("label_3")
        self.inputPass = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPass.setGeometry(QtCore.QRect(160, 110, 113, 20))
        self.inputPass.setObjectName("inputPass")
        self.logButton = QtWidgets.QPushButton(self.centralwidget)
        self.logButton.setGeometry(QtCore.QRect(130, 140, 75, 23))
        self.logButton.setObjectName("logButton")
        self.KlikDaftar = QtWidgets.QPushButton(self.centralwidget)
        self.KlikDaftar.setGeometry(QtCore.QRect(20, 210, 31, 23))
        self.KlikDaftar.setObjectName("KlikDaftar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 111, 21))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LOGIN"))
        self.label_2.setText(_translate("MainWindow", "ID"))
        self.label_3.setText(_translate("MainWindow", "PASSWORD"))
        self.logButton.setText(_translate("MainWindow", "LOGIN"))
        self.KlikDaftar.setText(_translate("MainWindow", "KLIK"))
        self.label_4.setText(_translate("MainWindow", "UNTUK MENDAFTAR"))
        self.logButton.clicked.connect(self.login)

    def login(self):
        import pymysql

        db = pymysql.connect(
            host="localhost",
            user="root",
            password="",
            database="loginRequest"
        )
        cursor = db.cursor()
        id = self.inputId.text()
        passwd = self.inputPass.text()
        sql = f"""INSERT INTO LOGIN (
            '{id}',
            '{passwd}'
            )"""

        cursor.execute(sql)
        db.commit()
        db.close()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
